### ISSUE TITLE
no-js html attribute

### ISSUE THREAD

**Issue by keyvanfatehi** [cwaring/meteor-modernizr#4]
need to add this as well

```js
Meteor.startup(function() {
  WebApp.addHtmlAttributeHook(function() {
    return {
      class: "no-js"
    }
  })
});
```

**Comment by cwaring** [comment]
Hi, thanks for the note. I don't think this amend is necessary as the HTML will never get built if the user has Javascript disabled. Correct me if I'm misunderstanding but I will consider this resolved otherwise.

**Comment by kfatehi** [comment]
I think it gets built server-side.
